spring.application.name=User_Service

spring.profiles.active=dev



#registering department service to service registry
#Modifying routing configuration to access department microservice by api gateway host:port
#server.port=${PORT:0}
server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}