spring.application.name=Department_Service

# H2 in memory database created properties with enabled h2 console
spring.datasource.url=jdbc:h2:mem:deptdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#enabling the H2 console : URL : http://localhost:8080/h2-console
spring.h2.console.enabled=true

#registering department service to service registry
#Modifying routing configuration to access department microservice by api gateway host:port
#server.port=${PORT:0}
server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}